# /home/wabukowabuko/Desktop/WebLMS/backend/users/serializers.py
from rest_framework import serializers
from .models import User
from django.contrib.auth.password_validation import validate_password

class UserSerializer(serializers.ModelSerializer):
    password = serializers.CharField(write_only=True, required=True, validators=[validate_password])
    user_code = serializers.CharField(read_only=True)  # Make user_code read-only, generated by the model

    class Meta:
        model = User
        fields = ['id', 'username', 'email', 'role', 'phone_number', 'student', 'password', 'user_code']

    def create(self, validated_data):
        # Remove password from validated_data to avoid saving it as plain text
        password = validated_data.pop('password', None)
        user = User(**validated_data)
        if password:
            user.set_password(password)
        user.save()
        return user
