# Generated by Django 4.2.19 on 2025-03-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='TEMP-0000', editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
